# Generated by Django 5.2.9 on 2025-12-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnittingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('difficulty', models.CharField(choices=[('easy', 'Легко'), ('medium', 'Средне'), ('hard', 'Сложно')], max_length=10, verbose_name='Сложность')),
                ('yarn_type', models.CharField(max_length=100, verbose_name='Тип пряжи')),
                ('needle_size', models.CharField(max_length=50, verbose_name='Размер спиц')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Схема вязания',
                'verbose_name_plural': 'Схемы вязания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('duration', models.IntegerField(help_text='Продолжительность в минутах', verbose_name='Длительность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YarnType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('composition', models.CharField(max_length=200, verbose_name='Состав')),
                ('thickness', models.CharField(max_length=50, verbose_name='Толщина')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за моток')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
            ],
            options={
                'verbose_name': 'Тип пряжи',
                'verbose_name_plural': 'Типы пряжи',
            },
        ),
    ]
